name: ferma_app
description: Professional tovuq fermasi boshqaruv ilovasi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Supabase
  supabase_flutter: ^2.3.1
  postgrest: ^2.0.0
  gotrue: ^2.0.0
  realtime_client: ^2.0.0
  storage_client: ^2.0.0
  functions_client: ^2.0.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Database & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  
  # UI & Animation
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  flutter_slidable: ^2.0.0
  fl_chart: ^0.63.0
  syncfusion_flutter_charts: ^23.1.44
  
  # Notifications
  flutter_local_notifications: ^19.4.0
  
  # Connectivity & Network
  connectivity_plus: ^6.1.5
  
  # Device & System Info
  device_info_plus: ^11.5.0
  
  # File Handling & Export
  open_file: ^3.3.2
  
  # Sharing
  share_plus: ^11.1.0
  
  # JSON Serialization
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  
  # Helpers
  equatable: ^2.0.5
  uuid: ^4.3.3
  collection: ^1.17.2
  rxdart: ^0.28.0
  crypto: ^3.0.3
  logger: ^2.0.2
  
  # Authentication
  local_auth: ^2.2.0
  local_auth_android: ^1.0.4
  
  # Permissions
  permission_handler: ^12.0.1
  
  # Image & Camera
  image_picker: ^1.0.4
  file_picker: ^10.3.2
  image_cropper: ^9.1.0
  cached_network_image: ^3.2.3
  
  # Date & Time
  intl: ^0.18.1
  build_runner: ^2.8.0
  analyzer: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Testing
  mockito: ^5.4.2
  integration_test:
    sdk: flutter
  
  # Build Tools
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "#121212"
  image: "assets/images/splash_logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  
  # Fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Roboto-Medium.ttf
  #         weight: 500
  
  # # Assets
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
