// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGlfJHlTPwIB8DP1EToFklSsJPAUFuS_A',
    appId: '1:447744204786:web:0ca3841d0347af5ed2556b',
    messagingSenderId: '447744204786',
    projectId: 'ferma-d4351',
    authDomain: 'ferma-d4351.firebaseapp.com',
    storageBucket: 'ferma-d4351.firebasestorage.app',
    measurementId: 'G-625EC4D46V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoHWXukPWNk_tsqMa4oU1pGdGr4kAC0uU',
    appId: '1:447744204786:android:263cbdd7875d319cd2556b',
    messagingSenderId: '447744204786',
    projectId: 'ferma-d4351',
    storageBucket: 'ferma-d4351.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANoCOQFQM4PCupK6KIbkP4BLdVXWQh9L4',
    appId: '1:447744204786:ios:682280652355b409d2556b',
    messagingSenderId: '447744204786',
    projectId: 'ferma-d4351',
    storageBucket: 'ferma-d4351.firebasestorage.app',
    iosBundleId: 'com.example.fermaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANoCOQFQM4PCupK6KIbkP4BLdVXWQh9L4',
    appId: '1:447744204786:ios:682280652355b409d2556b',
    messagingSenderId: '447744204786',
    projectId: 'ferma-d4351',
    storageBucket: 'ferma-d4351.firebasestorage.app',
    iosBundleId: 'com.example.fermaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGlfJHlTPwIB8DP1EToFklSsJPAUFuS_A',
    appId: '1:447744204786:web:6785e58a012327a3d2556b',
    messagingSenderId: '447744204786',
    projectId: 'ferma-d4351',
    authDomain: 'ferma-d4351.firebaseapp.com',
    storageBucket: 'ferma-d4351.firebasestorage.app',
    measurementId: 'G-VLKP9CVBN9',
  );
}
